### ISSUE TITLE
`<%= myobject.property %>`

### ISSUE THREAD

**Issue by gex** [wix/erb#1]
hello,

is there a way to compile templates with `<%= myobject.property %>` evaluations? we have some huge erb templates from an old project we'd like to not touch or rewrite for now.

bonus question: what about `<%= myobject.propery.to_i %>`?

**Comment by AvasDream** [comment]
What was your solution to this Problem? Have you implemented this functionality or used another way of importing ERB into node? Thanks in advance :)

**Comment by gex** [comment]
@AvasDream our `.erb` files were way too complex, they contained lots of ruby expressions and we didn't have the resource to write our own parser so we decided to rewrite the templates instead
